#!/bin/bash
#-------------------------------------------------------
# multi-configure
#-------------------------------------------------------
# This script is run in the ffmpeg source directory,
# to create out-of-tree build configurations to build
# the ffmpeg static libraries.
#
#  ./multi-configure  [all | win | x86 | arm | arm7 | host]
#
#-------------------------------------------------------
#
# This file is distributed under the GNU GENERAL PUBLIC LICENSE version 2.
# Please see the file `COPYING.GPLv2` for details.
#
# You are free to modify it, and distribute in any way you see fit,
# as long as you retain this notification and all copyrights herein.
#
# This software is provided without any warranty, explicit or implied.
#
# (c) Copyright 2015 - Patrick Horton


FFMPEG_VERSION=3.0
    # This is explicity set by the branch checkout

START_DIR=$PWD
    # The current working directory

HOST_PREFIX=_linux
    # Default host platform for the ndk
HOST_PLATFORM=linux-x86_64
    # The platform for this host within the ndk

if [ "$WINDIR" != "" ]
then
    HOST_PREFIX=_win
    HOST_PLATFORM=windows
fi

BUILD_BASE=$START_DIR/../_build/ffmpeg/$FFMPEG_VERSION/$HOST_PREFIX

VBOX_SHARED_FOLDER=1
    # This define has no effect on _win host builds.
    # On vbox _linux host builds, this fixes the strip
    # Protocol Error and symlinked makefile problems.


# These are the same flags as Lukas Lalinsky's stripped
# ffmpeg configuration, from ffmpeg-configure-mingw32.sh,
# from his guide on how to compile chromaprint for windows

# The multi-2.7/_linux/win build was crashing, related to AVX2_EXTERNAL.
# It also crashes in multi-tip == 2.7+/2.8dev
#
# I traced the crash thru chromaprint, into ffmpeg/libavcode/x86/fft_init.c,
# where it assigns AVX2_EXTERNAL on the working _win build, but not
# on the crashing _linux build.  The net result is that fft.asm is
# assembled differently in the two cases, and the only reason that
# AVX2_EXTERNAL is false on the _linux build is that the _linux ndk
# version of yasm apparently does not support "vextracti128 xmm0, ymm0, 0".
#
# At that point, I basically had three choices:
#
#     (1) follow the branch in ffmpeg and see if I can figure out why
#     it is crashing, and the "proper" fix to the assembly code.
#
#     (2) figure out why the yasm in the two ndk's is different.
#     I guess they must be since they were built to run on different
#     platforms. Then what, replace the "bad" on in the ndk?
#
#     (3) --disable-yasm on the _linux/win build ... and it worked.
#     Which implies that there is a bug, more or less, in the assembly
#     code when AVX2_EXTERNAL is false, and everything else is the same.
#
# Since it is not my goal to produce reference builds of fpcalc based on
# ffmpeg version 2.7, I am just disabling yasm for now, to get my test
# suite to run all the way through once.

# consider using these:

#    --disable-yasm
#    --disable-avx
#    --disable-avx2
#    --enable-memalign-hack

STD_CONFIG="
    --enable-static
    --disable-shared
    --disable-doc
    --disable-txtpages
    --disable-iconv


    --enable-debug
    --disable-avdevice
    --disable-avfilter
    --disable-swscale
    --disable-ffmpeg
    --disable-ffplay
    --disable-ffserver
    --disable-network
    --disable-muxers
    --disable-demuxers
    --enable-rdft
    --enable-demuxer=aac
    --enable-demuxer=ac3
    --enable-demuxer=ape
    --enable-demuxer=asf
    --enable-demuxer=flac
    --enable-demuxer=matroska_audio
    --enable-demuxer=mp3
    --enable-demuxer=mpc
    --enable-demuxer=mov
    --enable-demuxer=mpc8
    --enable-demuxer=ogg
    --enable-demuxer=tta
    --enable-demuxer=wav
    --enable-demuxer=wv
    --disable-bsfs
    --disable-filters
    --disable-parsers
    --enable-parser=aac
    --enable-parser=ac3
    --enable-parser=mpegaudio
    --disable-protocols
    --enable-protocol=file
    --disable-indevs
    --disable-outdevs
    --disable-encoders
    --disable-decoders
    --enable-decoder=aac
    --enable-decoder=ac3
    --enable-decoder=alac
    --enable-decoder=ape
    --enable-decoder=flac
    --enable-decoder=mp1
    --enable-decoder=mp2
    --enable-decoder=mp3
    --enable-decoder=mpc7
    --enable-decoder=mpc8
    --enable-decoder=tta
    --enable-decoder=vorbis
    --enable-decoder=wavpack
    --enable-decoder=wmav1
    --enable-decoder=wmav2
    --enable-decoder=pcm_alaw
    --enable-decoder=pcm_dvd
    --enable-decoder=pcm_f32be
    --enable-decoder=pcm_f32le
    --enable-decoder=pcm_f64be
    --enable-decoder=pcm_f64le
    --enable-decoder=pcm_s16be
    --enable-decoder=pcm_s16le
    --enable-decoder=pcm_s16le_planar
    --enable-decoder=pcm_s24be
    --enable-decoder=pcm_daud
    --enable-decoder=pcm_s24le
    --enable-decoder=pcm_s32be
    --enable-decoder=pcm_s32le
    --enable-decoder=pcm_s8
    --enable-decoder=pcm_u16be
    --enable-decoder=pcm_u16le
    --enable-decoder=pcm_u24be
    --enable-decoder=pcm_u24le
    --enable-decoder=rawvideo"


function configure_one
    # param1 = the build to perform.
    # The remainder of the params are -- items
    # to pass to the main ffmpeg configure script.
{
    WHICH=$1
    shift;

    echo -------------------------
    echo configure_one $WHICH
    echo -------------------------

    PREFIX=$BUILD_BASE/$WHICH/build
    mkdir -p $PREFIX
    cd $PREFIX

    INSTALL_DIR=$BUILD_BASE/$WHICH
    INSTALL_CFG="
        --bindir=$INSTALL_DIR/bin
        --libdir=$INSTALL_DIR/lib
        --incdir=$INSTALL_DIR/include
        --shlibdir=$INSTALL_DIR/bin"

    echo
    echo "CONFIGURATION: --prefix=$PREFIX $@" $INSTALL_CFG
    echo

    # do the actual configuration.

    $START_DIR/configure --prefix=$PREFIX "$@" $INSTALL_CFG $STD_CONFIG

    if [ $? -ne 0 ]
    then
        echo There was an error in configuring $1
        cd $START_DIR
        exit 1
    fi

    echo
    echo The configuration of $WHICH is finished
    echo
}



echo ---------------------------------------------
echo "multi-configure($FFMPEG_VERSION) $@ ..."
echo ---------------------------------------------

# variables common to all builds

COMMON_CFLAGS="-Os"
COMMON_BINDIR=$START_DIR/$INSTALL_DIR
COMMON_LIBDIR=$START_DIR/$INSTALL_DIR

# variables common to non-windows builds

NDK_ARCH="$NDK/platforms/android-9/arch"
NDK_CFLAGS="-fpic $COMMON_CFLAGS"
NDK_COMMON="--target-os=linux --enable-cross-compile --disable-pthreads"

# changes specific to VBOX_SHARED_FOLDERS, not on _win host

if [ "$WINDIR" == "" ]
then
    test $VBOX_SHARED_FOLDER && MULTI_STRIP="$START_DIR/multi-strip-ffmpeg"
fi


#------- loop through builds --------

for BUILD in "$@"
do

    if [ "$BUILD" == "allx" -o "$BUILD" == "win" ]
    then

        # --disable-yasm is 2.7+ specific fix for issue described above

        test "$WINDIR" == "" && CROSS_PREFIX=i586-mingw32msvc-
        test "$WINDIR" == "" && LINUX_SPECIFIC_OPTIONS="--disable-werrors --disable-yasm"
        test "$MULTI_STRIP" != "" && USE_STRIP="$MULTI_STRIP $CROSS_PREFIX"

        configure_one win \
            --arch=x86 \
            --target-os=mingw32 \
            --cross-prefix=$CROSS_PREFIX \
            --extra-cflags="$COMMON_CFLAGS" \
            --strip="$USE_STRIP" \
            $LINUX_SPECIFIC_OPTIONS \
            $COMMON
    fi


    if [ "$BUILD" == "all" -o "$BUILD" == "x86" ]
    then

        CROSS_PREFIX=$NDK/toolchains/x86-4.9/prebuilt/$HOST_PLATFORM/bin/i686-linux-android-
        test "$MULTI_STRIP" != "" && USE_STRIP="$MULTI_STRIP $CROSS_PREFIX"

        configure_one x86 \
            --arch=x86 \
            --sysroot=$NDK_ARCH-x86/ \
            --cross-prefix=$CROSS_PREFIX  \
            --extra-cflags="$NDK_CFLAGS" \
            --strip="$USE_STRIP" \
            $NDK_COMMON \
            $COMMON
    fi

    if [ "$BUILD" == "all" -o "$BUILD" == "arm" ]
    then

        CROSS_PREFIX=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/$HOST_PLATFORM/bin/arm-linux-androideabi-
        test "$MULTI_STRIP" != "" && USE_STRIP="$MULTI_STRIP $CROSS_PREFIX"

        configure_one arm \
            --arch=arm \
            --sysroot=$NDK_ARCH-arm/ \
            --cross-prefix=$CROSS_PREFIX \
            --extra-cflags="-marm $NDK_CFLAGS" \
            --strip="$USE_STRIP" \
            $NDK_COMMON \
            $COMMON
    fi


    if [ "$BUILD" == "all" -o "$BUILD" == "arm7" ]
    then

        CROSS_PREFIX=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/$HOST_PLATFORM/bin/arm-linux-androideabi-
        test "$MULTI_STRIP" != "" && USE_STRIP="$MULTI_STRIP $CROSS_PREFIX"

        # early versions use enable-armvfp, later versions use enable-vfp
        #    --extra-cflags="-mfloat-abi=softfp -mfpu=vfpv3  -marm $NDK_CFLAGS" \
            
        configure_one arm7 \
            --arch=arm \
            --cpu=armv7-a \
            --enable-vfp \
            --enable-neon \
            --sysroot=$NDK_ARCH-arm/ \
            --cross-prefix=$CROSS_PREFIX \
            --extra-cflags="-mfloat-abi=softfp -mfpu=vfpv3  -marm $NDK_CFLAGS" \
            --strip="$USE_STRIP" \
            $NDK_COMMON \
            $COMMON
    fi


    # multi-configure host must be explicitly provided
    # the host configure is not part of all (and does
    # not work on windows, use "win" build instead)

    if [ "$BUILD" == "host" ]
    then

        test "$MULTI_STRIP" != "" && USE_STRIP="$MULTI_STRIP"

        configure_one host \
            --disable-pthreads \
            --extra-cflags="$COMMON_CFLAGS" \
            --strip="$USE_STRIP" \
            $COMMON

    fi  # host build

done


echo
echo ---------------------------------------------
echo "multi-configure($FFMPEG_VERSION) finished"
echo ---------------------------------------------
cd $START_DIR
